test file formats

diff --git a/test/test_all.sh.in b/test/test_all.sh.in
--- a/test/test_all.sh.in
+++ b/test/test_all.sh.in
@@ -1,13 +1,16 @@
 #!/bin/sh
 
+# run the test workspaces
 for i in @TOP_SRCDIR@/test/workspaces/*; do
 	echo -n "testing `basename $i` ... "
 	if ! @TOP_SRCDIR@/src/nip2 --prefix=@TOP_SRCDIR@ --test $i ; then
-		exit 1
+		echo failed
+	else
+		echo ok
 	fi
-	echo ok
 done
 
+# load all the example workspaces too
 for i in @TOP_SRCDIR@/share/nip2/data/examples/*/*.ws; do
 	# have to skip these two, they use a non-free plugin
 	if test x"`basename $i`" = x"framing.ws" ; then
@@ -20,7 +23,23 @@ for i in @TOP_SRCDIR@/share/nip2/data/examples/*/*.ws; do
 	echo -n "testing `basename $i` ... "
 
 	if ! @TOP_SRCDIR@/src/nip2 --prefix=@TOP_SRCDIR@ --test $i ; then
-		exit 1
+		echo failed
+	else
+		echo ok
 	fi
-	echo ok
 done
+
+# run all the test scripts in scripts/, passing in @TOP_SRCDIR@ so they can
+# find stuff
+
+# these scripts put temp files here, we remove the dir on exit
+mkdir -p tmp
+
+for i in @TOP_SRCDIR@/test/scripts/*.sh; do
+	echo "running `basename $i`:"
+	if ! $i @TOP_SRCDIR@ ; then
+		echo "++ `basename $i` failed"
+	fi
+done
+
+rm -rf tmp
